const $=s=>document.querySelector(s);const page=document.body.dataset.page||'inici';const cats={'santa-cecilia':'Santa Cecília','festes-majors':'Festes Majors','terres-de-cruilla':'Terres de Cruïlla','nadal':'Nadal','altres':'Altres concerts'};
async function load(path){const r=await fetch(path);if(!r.ok)throw Error('No es pot carregar '+path);return r.json()}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function photo(path,alt){const safe=escapeHtml(path||'');return `<div class="cover fallback"><img src="${safe}" alt="${escapeHtml(alt)}" loading="lazy" onload="this.parentNode.classList.remove('fallback')" onerror="this.remove()"></div>`}
function formatDate(s){if(!s)return '';const d=new Date(s+'T12:00:00');return d.toLocaleDateString('ca-ES',{year:'numeric',month:'long',day:'numeric'})}
function card(x,kind='activitat'){const href=`detall.html?tipus=${kind}&id=${encodeURIComponent(x.id)}`;return `<a class="card" href="${href}">${photo(x.imatge,x.titol)}<div class="card-body"><div class="meta">${escapeHtml(kind==='curs'?'Cursos de direcció':kind==='iniciativa'?'Altres iniciatives':cats[x.categoria]||'Concert')} · ${formatDate(x.data||x.data_publicacio)}</div><h3>${escapeHtml(x.titol)}</h3><p>${escapeHtml(x.resum||'')}</p><span class="more">Descobreix-ne més ↗</span></div></a>`}
function empty(msg){return `<div class="empty">${escapeHtml(msg)}</div>`}
function sortDesc(a,b){return (b.data||b.data_publicacio||'').localeCompare(a.data||a.data_publicacio||'')}
async function start(){try{if(page==='inici'){const a=(await load('data/activitats.json')).sort(sortDesc);$('#destacats').innerHTML=a.filter(x=>x.destacat).slice(0,3).map(x=>card(x)).join('')||empty('Encara no hi ha concerts destacats.')}if(page==='concerts'){
 const a=(await load('data/activitats.json')).sort(sortDesc);
 const render=cat=>{
  const filtered=a.filter(x=>cat==='tots'||x.categoria===cat);
  const featured=filtered.find(x=>x.destacat)||filtered[0];
  const archive=filtered.filter(x=>x!==featured);
  $('#concert-featured').innerHTML=featured?`<a class="concert-feature" href="detall.html?tipus=activitat&id=${encodeURIComponent(featured.id)}">${photo(featured.imatge,featured.titol)}<div class="concert-feature-info"><div class="meta">${escapeHtml(cats[featured.categoria]||'Concert')} · ${escapeHtml(formatDate(featured.data))}</div><h2>${escapeHtml(featured.titol)}</h2><p>${escapeHtml(featured.resum||'')}</p><span class="more">DESCOBRIR EL CONCERT ↗</span></div></a>`:empty('No hi ha concerts en aquesta categoria.');
  $('#concert-list').innerHTML=archive.map(x=>card(x)).join('');
  $('#concert-count').textContent=archive.length?`${archive.length} ${archive.length===1?'activitat':'activitats'}`:'';
  document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===cat;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});
 };
 document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>render(b.dataset.filter)));render('tots')
}
if(page==='cursos'){const a=(await load('data/cursos.json')).sort(sortDesc);$('#cursos-list').innerHTML=a.map(x=>card(x,'curs')).join('')||empty('Pròximament publicarem la informació dels cursos de direcció.')}if(page==='altres'){const [c,i]=await Promise.all([load('data/cursos.json'),load('data/iniciatives.json')]);$('#cursos-list').innerHTML=c.sort(sortDesc).map(x=>card(x,'curs')).join('')||empty('Encara no hi ha cursos de direcció publicats.');$('#iniciatives-list').innerHTML=i.sort(sortDesc).map(x=>card(x,'iniciativa')).join('')||empty('Encara no hi ha altres iniciatives publicades.');$('#subvencions-list').innerHTML=s.sort(sortDesc).map(x=>card(x,'subvencio')).join('')||empty('Encara no hi ha subvencions publicades.')}if(page==='detall'){const q=new URLSearchParams(location.search);const kind=q.get('tipus')||'activitat';const file=kind==='curs'?'cursos':kind==='iniciativa'?'iniciatives':'activitats';const a=await load('data/'+file+'.json');const x=a.find(i=>i.id===q.get('id'));if(!x){$('#detall').innerHTML=empty('No hem trobat aquest contingut.');return}document.title=x.titol+' | AMS';const paras=Array.isArray(x.contingut)?x.contingut:[x.contingut].filter(Boolean);$('#detall').innerHTML=`<div class="eyebrow">${escapeHtml(kind==='curs'?'Cursos de direcció':kind==='iniciativa'?'Altres iniciatives':cats[x.categoria]||'Concerts')}</div><h1 style="font-size:clamp(2.4rem,5vw,4.4rem)">${escapeHtml(x.titol)}</h1><div class="meta">${formatDate(x.data||x.data_publicacio)} ${x.data_tipus==='publicacio'?'· Data de publicació':''}${x.lloc?' · '+escapeHtml(x.lloc):''}</div>${photo(x.imatge,x.titol)}${paras.map(t=>`<p>${escapeHtml(t)}</p>`).join('')}${x.import_eur?`<p><strong>Import concedit:</strong> ${Number(x.import_eur).toLocaleString('ca-ES',{style:'currency',currency:'EUR'})}</p>`:''}${x.font?`<p><a class="more" target="_blank" rel="noopener" href="${escapeHtml(x.font)}">Veure la publicació original ↗</a></p>`:''}<p><a class="btn ghost" href="${kind==='curs'||kind==='iniciativa'?'altres.html':'concerts.html'}">← Tornar</a></p>`}}catch(e){console.error(e);const target=$('#iniciatives-list')||$('#status')||$('#detall')||$('#concert-list')||$('#destacats')||$('#cursos-list')||$('#musics-list')||$('#subvencions-list');if(target)target.innerHTML=empty('No s’han pogut carregar les dades. Obre la web amb un servidor local (no amb file://).')}}document.addEventListener('DOMContentLoaded',()=>{const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();const b=$('.nav-toggle');b?.addEventListener('click',()=>{const open=$('.links').classList.toggle('open');b.setAttribute('aria-expanded',String(open))});document.querySelectorAll('.links a').forEach(a=>{if(a.getAttribute('href')===location.pathname.split('/').pop()||(location.pathname.endsWith('/')&&a.getAttribute('href')==='index.html'))a.classList.add('active')});start()});
