// FAQ: traduccions CA, ES, GL, PT i EN.
const faqTranslations = {
  "ca": {
    "faq": "Preguntes freqüents",
    "eyebrow": "PARTICIPACIÓ",
    "title": "Preguntes freqüents",
    "intro": "Resolem els dubtes més habituals de les bandes interessades a participar en el Certamen.",
    "ctaTitle": "No has trobat la resposta que buscaves?",
    "ctaText": "Contacta amb nosaltres i t’ajudarem a resoldre qualsevol dubte sobre la participació al Certamen.",
    "cta": "Demana informació ↗",
    "back": "Inici",
    "menu": "Menú",
    "contest": "El Certamen",
    "participation": "Participació",
    "contact": "Contacte",
    "g0": "Sobre el Certamen",
    "q0_0": "Qui pot participar en el Certamen?",
    "a0_0": "El Certamen està adreçat a bandes de música que compleixin els requisits establerts a les bases de l’edició corresponent. Quan es publiqui una nova convocatòria, hi trobaràs les condicions concretes de participació.",
    "q0_1": "Hi poden participar bandes d’altres països?",
    "a0_1": "Sí. El Certamen té vocació internacional i està obert a bandes de diferents procedències, sempre que compleixin les bases de l’edició.",
    "q0_2": "On se celebra el Certamen?",
    "a0_2": "El Certamen se celebra a la Sénia, a les Terres de l’Ebre, Catalunya.",
    "q0_3": "Quines categories o seccions hi ha?",
    "a0_3": "Les categories poden variar segons l’edició. La convocatòria i les bases indicaran les seccions disponibles i els requisits de cadascuna.",
    "g1": "Inscripció",
    "q1_0": "Quan s’obre el termini d’inscripció?",
    "a1_0": "Les dates d’inscripció es publicaran al web quan es convoqui cada edició. El formulari només estarà actiu durant el termini establert.",
    "q1_1": "Com puc inscriure la meva banda?",
    "a1_1": "Durant el termini d’inscripció podràs enviar la sol·licitud des de la secció Participació d’aquest web.",
    "q1_2": "Quina documentació cal presentar?",
    "a1_2": "La documentació necessària s’especificarà a les bases de cada edició i al mateix formulari d’inscripció.",
    "q1_3": "Enviar la inscripció significa que la banda ja està admesa?",
    "a1_3": "No. La recepció de la sol·licitud no implica automàticament l’admissió. L’organització comunicarà la resolució segons el procediment establert a les bases.",
    "g2": "Repertori i participació",
    "q2_0": "Quines obres ha d’interpretar cada banda?",
    "a2_0": "El repertori, la possible obra obligada i les condicions musicals es detallaran a les bases de l’edició corresponent.",
    "q2_1": "Quant pot durar l’actuació?",
    "a2_1": "La durada màxima o mínima, si n’hi ha, s’indicarà a les bases de cada edició.",
    "q2_2": "Es permeten músics de reforç?",
    "a2_2": "Les condicions relatives a la plantilla, músics de reforç, acreditacions i possibles límits s’establiran a les bases de cada edició.",
    "q2_3": "Cal enviar les partitures?",
    "a2_3": "Si l’organització necessita partitures o altra documentació musical, les bases indicaran què s’ha d’enviar, en quin format i dins de quin termini.",
    "g3": "Organització i resultats",
    "q3_0": "Quan es publicarà el programa i l’ordre d’actuació?",
    "a3_0": "El programa, els horaris i l’ordre d’actuació es publicaran al web quan hagin estat confirmats per l’organització.",
    "q3_1": "Hi haurà espais per escalfar o afinar?",
    "a3_1": "La informació logística per a les bandes participants es facilitarà abans del Certamen, juntament amb els horaris i les indicacions d’accés.",
    "q3_2": "Quan es publiquen els resultats?",
    "a3_2": "Els resultats oficials es comunicaran segons el desenvolupament de cada edició i posteriorment es podran consultar al web.",
    "q3_3": "Com puc fer una consulta que no apareix aquí?",
    "a3_3": "Pots utilitzar el formulari de contacte. Escriu-nos el teu dubte i l’organització et respondrà per correu electrònic."
  },
  "es": {
    "faq": "Preguntas frecuentes",
    "eyebrow": "PARTICIPACIÓN",
    "title": "Preguntas frecuentes",
    "intro": "Resolvemos las dudas más habituales de las bandas interesadas en participar en el Certamen.",
    "ctaTitle": "¿No has encontrado la respuesta que buscabas?",
    "ctaText": "Contacta con nosotros y te ayudaremos a resolver cualquier duda sobre la participación en el Certamen.",
    "cta": "Solicita información ↗",
    "back": "Inicio",
    "menu": "Menú",
    "contest": "El Certamen",
    "participation": "Participación",
    "contact": "Contacto",
    "g0": "Sobre el Certamen",
    "q0_0": "¿Quién puede participar en el Certamen?",
    "a0_0": "El Certamen está dirigido a bandas de música que cumplan los requisitos establecidos en las bases de la edición correspondiente. Cuando se publique una nueva convocatoria, encontrarás allí las condiciones concretas de participación.",
    "q0_1": "¿Pueden participar bandas de otros países?",
    "a0_1": "Sí. El Certamen tiene vocación internacional y está abierto a bandas de diferentes procedencias, siempre que cumplan las bases de la edición.",
    "q0_2": "¿Dónde se celebra el Certamen?",
    "a0_2": "El Certamen se celebra en la Sénia, en las Terres de l’Ebre, Cataluña.",
    "q0_3": "¿Qué categorías o secciones hay?",
    "a0_3": "Las categorías pueden variar según la edición. La convocatoria y las bases indicarán las secciones disponibles y los requisitos de cada una.",
    "g1": "Inscripción",
    "q1_0": "¿Cuándo se abre el plazo de inscripción?",
    "a1_0": "Las fechas de inscripción se publicarán en la web cuando se convoque cada edición. El formulario solo estará activo durante el plazo establecido.",
    "q1_1": "¿Cómo puedo inscribir a mi banda?",
    "a1_1": "Durante el plazo de inscripción podrás enviar la solicitud desde la sección Participación de esta web.",
    "q1_2": "¿Qué documentación hay que presentar?",
    "a1_2": "La documentación necesaria se especificará en las bases de cada edición y en el propio formulario de inscripción.",
    "q1_3": "¿Enviar la inscripción significa que la banda ya está admitida?",
    "a1_3": "No. La recepción de la solicitud no implica automáticamente la admisión. La organización comunicará la resolución según el procedimiento establecido en las bases.",
    "g2": "Repertorio y participación",
    "q2_0": "¿Qué obras debe interpretar cada banda?",
    "a2_0": "El repertorio, la posible obra obligada y las condiciones musicales se detallarán en las bases de la edición correspondiente.",
    "q2_1": "¿Cuánto puede durar la actuación?",
    "a2_1": "La duración máxima o mínima, si la hubiera, se indicará en las bases de cada edición.",
    "q2_2": "¿Se permiten músicos de refuerzo?",
    "a2_2": "Las condiciones relativas a la plantilla, músicos de refuerzo, acreditaciones y posibles límites se establecerán en las bases de cada edición.",
    "q2_3": "¿Hay que enviar las partituras?",
    "a2_3": "Si la organización necesita partituras u otra documentación musical, las bases indicarán qué debe enviarse, en qué formato y dentro de qué plazo.",
    "g3": "Organización y resultados",
    "q3_0": "¿Cuándo se publicarán el programa y el orden de actuación?",
    "a3_0": "El programa, los horarios y el orden de actuación se publicarán en la web cuando hayan sido confirmados por la organización.",
    "q3_1": "¿Habrá espacios para calentar o afinar?",
    "a3_1": "La información logística para las bandas participantes se facilitará antes del Certamen, junto con los horarios y las indicaciones de acceso.",
    "q3_2": "¿Cuándo se publican los resultados?",
    "a3_2": "Los resultados oficiales se comunicarán según el desarrollo de cada edición y posteriormente podrán consultarse en la web.",
    "q3_3": "¿Cómo puedo hacer una consulta que no aparece aquí?",
    "a3_3": "Puedes utilizar el formulario de contacto. Escríbenos tu duda y la organización te responderá por correo electrónico."
  },
  "gl": {
    "faq": "Preguntas frecuentes",
    "eyebrow": "PARTICIPACIÓN",
    "title": "Preguntas frecuentes",
    "intro": "Resolvemos as dúbidas máis habituais das bandas interesadas en participar no Certame.",
    "ctaTitle": "Non atopaches a resposta que buscabas?",
    "ctaText": "Contacta connosco e axudarémosche a resolver calquera dúbida sobre a participación no Certame.",
    "cta": "Solicita información ↗",
    "back": "Inicio",
    "menu": "Menú",
    "contest": "O Certame",
    "participation": "Participación",
    "contact": "Contacto",
    "g0": "Sobre o Certame",
    "q0_0": "Quen pode participar no Certame?",
    "a0_0": "O Certame está dirixido a bandas de música que cumpran os requisitos establecidos nas bases da edición correspondente. Cando se publique unha nova convocatoria, atoparás nelas as condicións concretas de participación.",
    "q0_1": "Poden participar bandas doutros países?",
    "a0_1": "Si. O Certame ten vocación internacional e está aberto a bandas de diferentes procedencias, sempre que cumpran as bases da edición.",
    "q0_2": "Onde se celebra o Certame?",
    "a0_2": "O Certame celébrase na Sénia, nas Terres de l’Ebre, Cataluña.",
    "q0_3": "Que categorías ou seccións hai?",
    "a0_3": "As categorías poden variar segundo a edición. A convocatoria e as bases indicarán as seccións dispoñibles e os requisitos de cada unha.",
    "g1": "Inscrición",
    "q1_0": "Cando se abre o prazo de inscrición?",
    "a1_0": "As datas de inscrición publicaranse na web cando se convoque cada edición. O formulario só estará activo durante o prazo establecido.",
    "q1_1": "Como podo inscribir a miña banda?",
    "a1_1": "Durante o prazo de inscrición poderás enviar a solicitude desde a sección Participación desta web.",
    "q1_2": "Que documentación hai que presentar?",
    "a1_2": "A documentación necesaria especificarase nas bases de cada edición e no propio formulario de inscrición.",
    "q1_3": "Enviar a inscrición significa que a banda xa está admitida?",
    "a1_3": "Non. A recepción da solicitude non implica automaticamente a admisión. A organización comunicará a resolución segundo o procedemento establecido nas bases.",
    "g2": "Repertorio e participación",
    "q2_0": "Que obras debe interpretar cada banda?",
    "a2_0": "O repertorio, a posible obra obrigada e as condicións musicais detallaranse nas bases da edición correspondente.",
    "q2_1": "Canto pode durar a actuación?",
    "a2_1": "A duración máxima ou mínima, se a houber, indicarase nas bases de cada edición.",
    "q2_2": "Permítense músicos de reforzo?",
    "a2_2": "As condicións relativas ao cadro de músicos, reforzos, acreditacións e posibles límites estableceranse nas bases de cada edición.",
    "q2_3": "Hai que enviar as partituras?",
    "a2_3": "Se a organización necesita partituras ou outra documentación musical, as bases indicarán que se debe enviar, en que formato e dentro de que prazo.",
    "g3": "Organización e resultados",
    "q3_0": "Cando se publicarán o programa e a orde de actuación?",
    "a3_0": "O programa, os horarios e a orde de actuación publicaranse na web cando sexan confirmados pola organización.",
    "q3_1": "Haberá espazos para quentar ou afinar?",
    "a3_1": "A información loxística para as bandas participantes facilitarase antes do Certame, xunto cos horarios e as indicacións de acceso.",
    "q3_2": "Cando se publican os resultados?",
    "a3_2": "Os resultados oficiais comunicaranse segundo o desenvolvemento de cada edición e posteriormente poderán consultarse na web.",
    "q3_3": "Como podo facer unha consulta que non aparece aquí?",
    "a3_3": "Podes utilizar o formulario de contacto. Escríbenos a túa dúbida e a organización responderache por correo electrónico."
  },
  "pt": {
    "faq": "Perguntas frequentes",
    "eyebrow": "PARTICIPAÇÃO",
    "title": "Perguntas frequentes",
    "intro": "Respondemos às dúvidas mais habituais das bandas interessadas em participar no Certame.",
    "ctaTitle": "Não encontraste a resposta que procuravas?",
    "ctaText": "Contacta connosco e ajudamos-te a esclarecer qualquer dúvida sobre a participação no Certame.",
    "cta": "Pede informações ↗",
    "back": "Início",
    "menu": "Menu",
    "contest": "O Certame",
    "participation": "Participação",
    "contact": "Contacto",
    "g0": "Sobre o Certame",
    "q0_0": "Quem pode participar no Certame?",
    "a0_0": "O Certame destina-se a bandas de música que cumpram os requisitos estabelecidos no regulamento da respetiva edição. Quando for publicada uma nova convocatória, encontrarás aí as condições concretas de participação.",
    "q0_1": "Podem participar bandas de outros países?",
    "a0_1": "Sim. O Certame tem vocação internacional e está aberto a bandas de diferentes proveniências, desde que cumpram o regulamento da edição.",
    "q0_2": "Onde se realiza o Certame?",
    "a0_2": "O Certame realiza-se em La Sénia, nas Terres de l’Ebre, Catalunha.",
    "q0_3": "Que categorias ou secções existem?",
    "a0_3": "As categorias podem variar consoante a edição. A convocatória e o regulamento indicarão as secções disponíveis e os requisitos de cada uma.",
    "g1": "Inscrição",
    "q1_0": "Quando abre o período de inscrições?",
    "a1_0": "As datas de inscrição serão publicadas no site quando cada edição for anunciada. O formulário só estará ativo durante o período estabelecido.",
    "q1_1": "Como posso inscrever a minha banda?",
    "a1_1": "Durante o período de inscrições poderás enviar a candidatura através da secção Participação deste site.",
    "q1_2": "Que documentação é necessária?",
    "a1_2": "A documentação necessária será especificada no regulamento de cada edição e no próprio formulário de inscrição.",
    "q1_3": "Enviar a inscrição significa que a banda já foi admitida?",
    "a1_3": "Não. A receção da candidatura não implica automaticamente a admissão. A organização comunicará a decisão de acordo com o procedimento estabelecido no regulamento.",
    "g2": "Repertório e participação",
    "q2_0": "Que obras deve interpretar cada banda?",
    "a2_0": "O repertório, a eventual obra obrigatória e as condições musicais serão detalhados no regulamento da respetiva edição.",
    "q2_1": "Quanto pode durar a atuação?",
    "a2_1": "A duração máxima ou mínima, caso exista, será indicada no regulamento de cada edição.",
    "q2_2": "São permitidos músicos de reforço?",
    "a2_2": "As condições relativas ao efetivo da banda, músicos de reforço, acreditações e eventuais limites serão estabelecidas no regulamento de cada edição.",
    "q2_3": "É necessário enviar as partituras?",
    "a2_3": "Se a organização necessitar de partituras ou outra documentação musical, o regulamento indicará o que deve ser enviado, em que formato e dentro de que prazo.",
    "g3": "Organização e resultados",
    "q3_0": "Quando serão publicados o programa e a ordem de atuação?",
    "a3_0": "O programa, os horários e a ordem de atuação serão publicados no site quando forem confirmados pela organização.",
    "q3_1": "Haverá espaços para aquecer ou afinar?",
    "a3_1": "A informação logística para as bandas participantes será fornecida antes do Certame, juntamente com os horários e as indicações de acesso.",
    "q3_2": "Quando são publicados os resultados?",
    "a3_2": "Os resultados oficiais serão comunicados de acordo com o desenvolvimento de cada edição e posteriormente poderão ser consultados no site.",
    "q3_3": "Como posso colocar uma questão que não aparece aqui?",
    "a3_3": "Podes utilizar o formulário de contacto. Envia-nos a tua dúvida e a organização responderá por correio eletrónico."
  },
  "en": {
    "faq": "Frequently asked questions",
    "eyebrow": "PARTICIPATION",
    "title": "Frequently asked questions",
    "intro": "Answers to common questions from bands interested in taking part in the Competition.",
    "ctaTitle": "Didn’t find the answer you were looking for?",
    "ctaText": "Contact us and we will help with any questions about taking part in the Competition.",
    "cta": "Request information ↗",
    "back": "Home",
    "menu": "Menu",
    "contest": "The Competition",
    "participation": "Participation",
    "contact": "Contact",
    "g0": "About the Competition",
    "q0_0": "Who can take part in the Competition?",
    "a0_0": "The Competition is open to wind bands that meet the requirements set out in the rules for the relevant edition. When a new call is published, the specific participation requirements will be available there.",
    "q0_1": "Can bands from other countries take part?",
    "a0_1": "Yes. The Competition has an international outlook and welcomes bands from different countries, provided they meet the rules for that edition.",
    "q0_2": "Where is the Competition held?",
    "a0_2": "The Competition is held in La Sénia, Terres de l’Ebre, Catalonia.",
    "q0_3": "What categories or sections are available?",
    "a0_3": "Categories may vary from one edition to another. The call and rules will specify the available sections and the requirements for each one.",
    "g1": "Registration",
    "q1_0": "When does registration open?",
    "a1_0": "Registration dates will be published on the website when each edition is announced. The form will only be active during the stated registration period.",
    "q1_1": "How can I register my band?",
    "a1_1": "During the registration period, you can submit an application through the Participation section of this website.",
    "q1_2": "What documents are required?",
    "a1_2": "The required documents will be specified in the rules for each edition and in the registration form itself.",
    "q1_3": "Does submitting an application mean the band has been accepted?",
    "a1_3": "No. Receipt of an application does not automatically mean acceptance. The organisation will communicate its decision according to the procedure set out in the rules.",
    "g2": "Repertoire and participation",
    "q2_0": "What pieces must each band perform?",
    "a2_0": "The repertoire, any compulsory piece and the musical requirements will be detailed in the rules for the relevant edition.",
    "q2_1": "How long can the performance be?",
    "a2_1": "Any minimum or maximum performance duration will be stated in the rules for each edition.",
    "q2_2": "Are additional or guest musicians allowed?",
    "a2_2": "Rules concerning band personnel, additional musicians, accreditation and any limits will be established in the rules for each edition.",
    "q2_3": "Do we need to submit scores?",
    "a2_3": "If scores or other musical documents are required, the rules will explain what must be submitted, in which format and by what deadline.",
    "g3": "Organisation and results",
    "q3_0": "When will the programme and performance order be published?",
    "a3_0": "The programme, timetable and performance order will be published on the website once confirmed by the organisation.",
    "q3_1": "Will there be spaces to warm up or tune?",
    "a3_1": "Logistical information for participating bands will be provided before the Competition, together with schedules and access instructions.",
    "q3_2": "When are the results published?",
    "a3_2": "Official results will be announced in accordance with each edition’s schedule and will subsequently be available on the website.",
    "q3_3": "How can I ask a question that is not answered here?",
    "a3_3": "Use the contact form to send us your question. The organisation will reply by email."
  }
};
function setFaqLanguage(lang){const d=faqTranslations[lang];if(!d)return;document.documentElement.lang=lang;document.querySelectorAll('[data-faq]').forEach(el=>{const v=d[el.dataset.faq];if(v!==undefined)el.textContent=v;});document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lang===lang)));document.title=d.title+' · Certamen Vila de la Sénia';try{localStorage.setItem('certamen-lang',lang)}catch(_){}}document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setFaqLanguage(b.dataset.lang)));const mb=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav');if(mb&&nav){mb.addEventListener('click',()=>{const o=nav.classList.toggle('open');mb.setAttribute('aria-expanded',String(o))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');mb.setAttribute('aria-expanded','false')}));}try{const l=localStorage.getItem('certamen-lang');if(l&&faqTranslations[l])setFaqLanguage(l)}catch(_){}